#!/bin/bash
set -e
set -o pipefail

# add group
if ! getent group | grep -q "^vertcore:" ; then
    echo "Creating system group: vertcore"
    groupadd --system vertcore
fi

# add user
if ! getent passwd | grep -q "^vertcore:"; then
    echo "Creating vertcore system user"
    useradd --gid "vertcore" --system -m vertcore
fi

# build nodejs addons
cd "/usr/opt/vertcore"
SKIP_BITCOIN_DOWNLOAD=1 npm rebuild

# setup data directory
mkdir -p "/home/vertcore/.vertcore/data"
chown -R vertcore:vertcore "/home/vertcore/.vertcore"

# start vertcore
if hash service 2> /dev/null; then
    service vertcore start || echo "vertcore could not be registered or started"
elif hash start 2> /dev/null; then
    start vertcore || echo "vertcore could not be registered or started"
elif hash systemctl 2> /dev/null; then
    {
        systemctl enable "vertcore.service" && \
            systemctl start "vertcore.service"
    } || echo "vertcore could not be registered or started"
else
    echo 'Your system does not appear to use upstart or systemd, so vertcore could not be started'
fi
