#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service vertcore stop || echo "vertcore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "vertcore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "vertcore.service" || echo "vertcore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so vertcore could not be stopped"
fi
